"""antras zingsnis v6

Revision ID: 38bffe38d34c
Revises: 671eb8762aeb
Create Date: 2023-09-29 23:29:31.200409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '38bffe38d34c'
down_revision: Union[str, None] = '671eb8762aeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'permissions',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'permissions',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
