"""antras zingsnis v5

Revision ID: 671eb8762aeb
Revises: 14f597a54f77
Create Date: 2023-09-29 23:23:03.939249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '671eb8762aeb'
down_revision: Union[str, None] = '14f597a54f77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'permissions',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'permissions',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
