"""antras zingsnis v11

Revision ID: e734c4ba7a43
Revises: e216f34f0625
Create Date: 2023-09-30 00:10:24.450934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e734c4ba7a43'
down_revision: Union[str, None] = 'e216f34f0625'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_company')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_company', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
